---
#title: "Información sobre el curso"
toc: true
#self-contained: true
---

## Información sobre el curso

::: {.callout-note appearance="minimal" icon="false"}
## 

-   En el curso usaremos 3 programas. Principalmente usaremos [R](https://cran.r-project.org/){target="_blank"} a través de [RStudio](https://www.rstudio.com/products/rstudio/download/#download){target="_blank"}. En la última sesión del curso también usaremos [Quarto](https://quarto.org/).

-   Se recomienda tener instaladas **versiones recientes** de los 3 programas. Tienes instrucciones de instalación más abajo

-   Es muy-muy conveniente acudir al curso con tu propio ordenador.

-   Los materiales que usaremos están en [Materiales](materiales.qmd).
:::

## Horario y aula

::: {.callout-note appearance="minimal" icon="false"}
## 

| Día                     | Hora          | Lugar                                    | Profesor     |
|-------------------------|---------------|------------------------------------------|--------------|
| 12 de junio (lunes)     | 16:00 a 20:00 | Aula 302 (Aulario Sur, Campus Tarongers) | Vicente      |
| 13 de junio (martes)    | 16:00 a 20:00 | Aula 302 (Aulario Sur, Campus Tarongers) | Pedro        |
| 15 de junio (jueves)    | 16:00 a 20:00 | Aula 302 (Aulario Sur, Campus Tarongers) | Pedro        |
| 19 de junio (lunes)     | 16:00 a 20:00 | Aula 302 (Aulario Sur, Campus Tarongers) | Vicente      |
| 20 de junio (martes)    | 16:00 a 20:00 | Aula 302 (Aulario Sur, Campus Tarongers) | Vicente      |
| 22 de junio (jueves)    | 16:00 a 20:00 | Aula 302 (Aulario Sur, Campus Tarongers) | Pedro        |



:::

```{r}
#| echo: false
#| eval: false
library(leaflet)
leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
addMarkers(lng = -0.34371, lat = 39.47795, popup = "Aulario Sur del Campus de Tarongers)")
```

## Lugar

Las clases se desarrollarán en:

::: {.callout-note collapse="true" appearance="default" icon="false"}
## **Aula 302** del **aulario Sur del Campus de Tarongers** (Universitat de València)

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3079.620706245074!2d-0.34585198436775366!3d39.47789667012178!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd604885bfd7753f%3A0x9ce3658009b3a33!2sAulari%20Sud%20%2F%20Aulario%20Sur!5e0!3m2!1ses!2ses!4v1678529561371!5m2!1ses!2ses" width="870" height="500" style="border:0;" allowfullscreen loading="lazy" referrerpolicy="no-referrer-when-downgrade">

</iframe>
:::

-   Si el mapa anterior no se te muestra, también puedes verlo [aquí](https://goo.gl/maps/sKgDr3U2gwVsKHxL6){target="_blank"}

## Programas (instalación)

::: {.callout-important collapse="false" appearance="default" icon="false"}
## Instalación de R y RStudio

-   En el curso usaremos 3 programas: R, RStudio y Quarto, así que tenemos que instalarlos

-   Has de instalar los programas en este orden:

    1.  R: <https://cran.r-project.org/>{target="_blank"}

    2.  RStudio: <https://posit.co/download/rstudio-desktop/>{target="_blank"}
    
    3. Quarto: <https://quarto.org/docs/download/>{target="_blank"}

-   Para ello, solamente has de descargar las versiones de los instaladores adecuadas para tu sistema operativo
:::

<br>
